# Generated by Django 3.1.3 on 2020-11-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0003_auto_20201120_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='latitude',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='departments',
            name='longitude',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
